name: mpush
description: MPush client for Flutter, you can use this plugin to interact with MPush.
documentation: https://docs.mpush.cloud
version: 1.0.0
authors:
  - Lorenzo Oliveto <lorenzo.oliveto@mumbleideas.it>
  - Enrico Ori <enrico.ori@mumbleideas.it>
homepage: https://github.com/Mumble-SRL/MPush-Flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  device_info: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mumble.mpush
        pluginClass: MpushPlugin
      ios:
        pluginClass: MpushPlugin
