name: mpush
description: MPush client for Flutter, you can use this plugin to interact with MPush.
version: 1.1.4
homepage: https://github.com/Mumble-SRL/MPush-Flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  android_id: ^0.4.0
  http: ^1.2.2
  device_info_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mumble.mpush
        pluginClass: MpushPlugin
      ios:
        pluginClass: MpushPlugin
