name: mpush
description: MPush client for Flutter, you can use this plugin to interact with MPush.
version: 0.0.1+2
authors:
  - Lorenzo Oliveto <lorenzo.oliveto@mumbleideas.it>
  - Enrico Ori <enrico.ori@mumbleideas.it>
homepage: https://github.com/Mumble-SRL/MPush-Flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  device_info: ^0.4.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mumble.mpush
        pluginClass: MpushPlugin
      ios:
        pluginClass: MpushPlugin
