name: mpush
description: MPush client for Flutter, you can use this plugin to interact with MPush.
version: 1.0.7
homepage: https://github.com/Mumble-SRL/MPush-Flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  android_id: ^0.0.7
  http: ^0.13.5
  device_info_plus: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.mumble.mpush
        pluginClass: MpushPlugin
      ios:
        pluginClass: MpushPlugin
